name: Fresh package build

on: 
  workflow_dispatch

jobs:
  build_pkg:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Set up environment
      run: |
        cd /tmp/
        ARCHIVE_ORG_ITEM_NAME="commontools"
        echo "ARCHIVE_ORG_ITEM_NAME=$ARCHIVE_ORG_ITEM_NAME" >> $GITHUB_ENV

        RELEASE_NAME="$(date '+%Y%m%d')"
        echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
        
        FRESH_INSTALLERS_DIR="/tmp/third-parties-fresh-installers/"
        FRESH_INSTALLERS_ZIP="/tmp/third-parties-fresh-installers.zip"
        FRESH_INSTALLERS_ZIP_SHA256="/tmp/third-parties-fresh-installers.zip.sha256"
        echo "FRESH_INSTALLERS_DIR=$FRESH_INSTALLERS_DIR" >> $GITHUB_ENV
        echo "FRESH_INSTALLERS_ZIP=$FRESH_INSTALLERS_ZIP" >> $GITHUB_ENV
        echo "FRESH_INSTALLERS_ZIP_SHA256=$FRESH_INSTALLERS_ZIP_SHA256" >> $GITHUB_ENV

        mkdir -p "$FRESH_INSTALLERS_DIR"
        
    - name: Install prerequisites
      run: |
        cd /tmp/
        git clone https://github.com/maaaaz/patchmypcdl.git
        git clone https://github.com/maaaaz/chocodl.git
        pip install -r ./patchmypcdl/requirements.txt

    - name: Download files
      run: |
        cd /tmp/
        python "/tmp/patchmypcdl/patchmypcdl.py" -i "$GITHUB_WORKSPACE/_Resources/patchmypc_inputs.txt"
        aria2c --log-level error --console-log-level error -i "$GITHUB_WORKSPACE/_Resources/aria2c_inputs.txt"
        
    - name: List files
      run: |
        du -sh "$FRESH_INSTALLERS_DIR"
        find "$FRESH_INSTALLERS_DIR" -type f | sort

    - name: Create zip and compute hash
      run: |
        zip -r "$FRESH_INSTALLERS_ZIP" "$FRESH_INSTALLERS_DIR"
        ls -alh "$FRESH_INSTALLERS_ZIP"

        sha256sum --tag "$FRESH_INSTALLERS_ZIP" | tee "$FRESH_INSTALLERS_ZIP_SHA256"
        
    - name: Push to archive.org
      env:   
        SECRET_ARCHIVE_ORG_LOGIN: ${{ secrets.SECRET_ARCHIVE_ORG_LOGIN }}
        SECRET_ARCHIVE_ORG_PASSWORD: ${{ secrets.SECRET_ARCHIVE_ORG_PASSWORD }}
      run: |
        cd /tmp/
        /tmp/ia configure --username=$SECRET_ARCHIVE_ORG_LOGIN --password=$SECRET_ARCHIVE_ORG_PASSWORD

        # /tmp/ia upload -q $ARCHIVE_ORG_ITEM_NAME $FRESH_INSTALLERS_ZIP --metadata="mediatype:software"
        # /tmp/ia upload -q $ARCHIVE_ORG_ITEM_NAME $FRESH_INSTALLERS_ZIP_SHA256 --metadata="mediatype:texts"

    - name: Create a new Github release
      uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564 #v2.0.4
      with:
        body_path: ${{ env.FRESH_INSTALLERS_ZIP_SHA256 }}
        name: ${{ env.RELEASE_NAME }}
        tag_name: ${{ env.RELEASE_NAME }}
